version: "3.7"

services:
  php:
    build:
      context: ./docker/images/php
    container_name: iot-php
    volumes:
      - './web:/var/www/html'
      - './docker/dashboard:/var/www/dashboard'
    depends_on:
      - mariadb
    networks:
      - iot-network

  nginx:
    image: nginx:latest
    container_name: iot-nginx
    ports:
      - "${WEBSERVER_PORT}:80"
    depends_on:
      - php
      - phpmyadmin
    volumes:
      - './web:/var/www/html'
      - './docker/config/nginx:/etc/nginx/conf.d'
      - './docker/dashboard:/var/www/dashboard'
    networks:
      - iot-network

  mariadb:
    image: mariadb:latest
    container_name: iot-mariadb
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - './docker/config/mariadb:/var/lib/mysql'
    networks:
      - iot-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: iot-phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=${MYSQL_PORT}
      - PMA_ARBITRARY=1
    ports:
      - "8081:80"  # Exposing phpMyAdmin on port 8081
    depends_on:
      - mariadb
    volumes:
      - './docker/config/phpmyadmin/sessions:/sessions'
    networks:
      - iot-network

  tunnel:
    build:
      context: ./docker/images/tunnel
    container_name: iot-tunnel
    platform: linux/amd64  # Specify platform to match the image
    environment:
      - WEBSERVER_PORT=${WEBSERVER_PORT}
      - TUNNEL_SUBDOMAIN=${HVA_USERNAME}
    depends_on:
      - nginx
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge
